'use strict'; // code generated by pbf v3.2.0

var MsgType = exports.MsgType = {
    "changes": {
        "value": 0,
        "options": {}
    }
};

// Position ========================================

var Position = exports.Position = {};

Position.read = function (pbf, end) {
    return pbf.readFields(Position._readField, {x: 0, y: 0, z: 0}, end);
};
Position._readField = function (tag, obj, pbf) {
    if (tag === 0) obj.x = pbf.readVarint(true);
    else if (tag === 1) obj.y = pbf.readVarint(true);
    else if (tag === 2) obj.z = pbf.readVarint(true);
};
Position.write = function (obj, pbf) {
    if (obj.x) pbf.writeVarintField(0, obj.x);
    if (obj.y) pbf.writeVarintField(1, obj.y);
    if (obj.z) pbf.writeVarintField(2, obj.z);
};

// Rotation ========================================

var Rotation = exports.Rotation = {};

Rotation.read = function (pbf, end) {
    return pbf.readFields(Rotation._readField, {x: 0, y: 0, z: 0, w: 0}, end);
};
Rotation._readField = function (tag, obj, pbf) {
    if (tag === 0) obj.x = pbf.readFloat();
    else if (tag === 1) obj.y = pbf.readFloat();
    else if (tag === 2) obj.z = pbf.readFloat();
    else if (tag === 3) obj.w = pbf.readFloat();
};
Rotation.write = function (obj, pbf) {
    if (obj.x) pbf.writeFloatField(0, obj.x);
    if (obj.y) pbf.writeFloatField(1, obj.y);
    if (obj.z) pbf.writeFloatField(2, obj.z);
    if (obj.w) pbf.writeFloatField(3, obj.w);
};

// Changes ========================================

var Changes = exports.Changes = {};

Changes.read = function (pbf, end) {
    return pbf.readFields(Changes._readField, {type: 0, time: 0, position: null, rotation: null, lastShotTime: 0, hitBodyIds: []}, end);
};
Changes._readField = function (tag, obj, pbf) {
    if (tag === 0) obj.type = pbf.readVarint();
    else if (tag === 1) obj.time = pbf.readVarint(true);
    else if (tag === 2) obj.position = Position.read(pbf, pbf.readVarint() + pbf.pos);
    else if (tag === 3) obj.rotation = Rotation.read(pbf, pbf.readVarint() + pbf.pos);
    else if (tag === 4) obj.lastShotTime = pbf.readVarint(true);
    else if (tag === 5) pbf.readPackedVarint(obj.hitBodyIds);
};
Changes.write = function (obj, pbf) {
    if (obj.type) pbf.writeVarintField(0, obj.type);
    if (obj.time) pbf.writeVarintField(1, obj.time);
    if (obj.position) pbf.writeMessage(2, Position.write, obj.position);
    if (obj.rotation) pbf.writeMessage(3, Rotation.write, obj.rotation);
    if (obj.lastShotTime) pbf.writeVarintField(4, obj.lastShotTime);
    if (obj.hitBodyIds) pbf.writePackedVarint(5, obj.hitBodyIds);
};
