-- MySQL Script generated by MySQL Workbench
-- Sat 02 Mar 2019 16:07:41 +07
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema airplanes
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `airplanes` ;

-- -----------------------------------------------------
-- Schema airplanes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `airplanes` DEFAULT CHARACTER SET utf8 ;
USE `airplanes` ;

-- -----------------------------------------------------
-- Table `airplanes`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airplanes`.`users` ;

CREATE TABLE IF NOT EXISTS `airplanes`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `kills` INT NULL DEFAULT 0,
  `points` INT NULL DEFAULT 0,
  `deaths` INT NULL DEFAULT 0,
  `password` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airplanes`.`achievements`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airplanes`.`achievements` ;

CREATE TABLE IF NOT EXISTS `airplanes`.`achievements` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `description` LONGTEXT NULL DEFAULT NULL,
  `machine_name` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airplanes`.`achievements_has_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airplanes`.`achievements_has_users` ;

CREATE TABLE IF NOT EXISTS `airplanes`.`achievements_has_users` (
  `achievements_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`achievements_id`, `users_id`),
  INDEX `fk_achievements_has_users_users1_idx` (`users_id` ASC),
  INDEX `fk_achievements_has_users_achievements_idx` (`achievements_id` ASC),
  CONSTRAINT `fk_achievements_has_users_achievements`
    FOREIGN KEY (`achievements_id`)
    REFERENCES `airplanes`.`achievements` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_achievements_has_users_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `airplanes`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
